name: servant_industry_hiring
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  shared_preferences: ^2.3.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1

  firebase_core: ^3.2.0
#  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
#  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.2
  cached_network_image: ^3.4.0

  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  image_picker: ^1.1.2
  pinput: ^5.0.0
  outline_search_bar: ^2.3.0
  salomon_bottom_bar: ^3.3.2

  easy_localization: ^3.0.3
  flutter_masked_text2: ^0.9.1
  file_picker: ^6.1.1
  flutter_custom_clippers: ^2.1.0

#  google maps
  google_maps_flutter: ^2.9.0
  google_polyline_algorithm: ^3.1.0

  intl: ^0.19.0
  syncfusion_flutter_charts: ^25.2.4
  video_player: ^2.2.18
  flutter_stripe: ^10.1.1

  social_media_recorder: null
  voice_message_package: null
  animated_rating_stars: ^1.0.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.3.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

  fonts:
    - family: jmaeel
      fonts:
        - asset: assets/font/jmaeel.ttf